# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 布劳格
url: "https://deepsecret.github.io/" # the base hostname & protocol for your site
baseurl: "/blog"
photourl: "https://blogliuhao-1301379188.cos.accelerate.myqcloud.com"

# Build settings
markdown: kramdown
permalink: /:year-:month-:day/:title

paginate: 15
paginate_path: "/archive/:num/"