# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 早安，地球
email: liuhao1990@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   A personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.liuhao.im" # the base hostname & protocol for your site
photourl: "https://blogliuhao-1301379188.cos.ap-hongkong.myqcloud.com"

# Build settings
markdown: kramdown
permalink: /:year-:month-:day/:title

paginate: 1
paginate_path: "/:num/"

collections:
   category:
      output: true

defaults:
   -
      scope:
         path: ""
         type: category
      values:
         layout: "category"